spring:
  application:
    name: localapibackend
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/postgres?autoReconnect=true}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 5
      minimumIdle: 2
      connectionTimeout: 10000
  liquibase:
    enabled: false
    change-log: classpath:/liquibase/latest/update.xml
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        default_schema: public
        show_sql: false
        format_sql: false
        use_sql_comments: false

logging:
  level:
    root: DEBUG

server:
  port: 8081
  servlet:
    context-path: /ui
#  compression:
#    enabled: true
#  tomcat:
#    accesslog:
#      enabled: true
#      suffix: .log
#      prefix: access_log
#      file-date-format: .yyyy-MM-dd
#      directory: logs
#      pattern: common
#    basedir: /var/log/tomcat

springdoc:
  use-root-path: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    displayOperationId: true
    displayRequestDuration: true
    disable-swagger-default-url: true
    use-fqn: true

ui:
  environment: development
  swagger: true

appliance:
  url: http://localhost:8080

voucher:
  url: http://localhost:8080



